import { Question } from "./types";

export const QUESTIONS: Question[] = [
  {
    id: "q1_physical",
    number: 1,
    category: "Physical Activity",
    categoryIcon: "💪",
    prompt: "When life gets busy, how often do you still make time to move your body?",
    subtitle: "Physical vitality and exertion form the bedrock of your character's foundation.",
    options: [
      {
        id: "p1",
        text: "Almost never — physical movement takes a backseat when demands pile up.",
        statModifiers: { strength: 4, energy: 5 },
        archetypeWeight: { scholar: 3 },
      },
      {
        id: "p2",
        text: "Occasionally — once or twice a week when I find an open pocket of time.",
        statModifiers: { strength: 10, energy: 10 },
        archetypeWeight: { strategist: 2 },
      },
      {
        id: "p3",
        text: "A few times a week — I aim for regular workouts, sports, or brisk walks.",
        statModifiers: { strength: 18, energy: 16 },
        archetypeWeight: { guardian: 4, warrior: 3 },
      },
      {
        id: "p4",
        text: "Most days — physical exercise is an integrated, non-negotiable anchor.",
        statModifiers: { strength: 25, energy: 22 },
        archetypeWeight: { warrior: 6, guardian: 3 },
      },
      {
        id: "p5",
        text: "Nearly every day — high physical intensity and movement are central to who I am.",
        statModifiers: { strength: 30, energy: 26 },
        archetypeWeight: { warrior: 8 },
      },
    ],
  },
  {
    id: "q2_consistency",
    number: 2,
    category: "Consistency & Willpower",
    categoryIcon: "🔥",
    prompt: "When you decide to build a new habit, what usually happens?",
    subtitle: "The forge of discipline determines how long you can sustain a standard.",
    options: [
      {
        id: "c1",
        text: "I struggle to start — inertia and overthinking often keep me grounded.",
        statModifiers: { discipline: 5 },
        archetypeWeight: { scholar: 2 },
      },
      {
        id: "c2",
        text: "I start with burst motivation, but often fade after several days.",
        statModifiers: { discipline: 10, energy: 12 },
        archetypeWeight: { explorer: 4 },
      },
      {
        id: "c3",
        text: "I stay consistent for a few weeks, but disruptions can derail my streak.",
        statModifiers: { discipline: 18, focus: 14 },
        archetypeWeight: { builder: 3 },
      },
      {
        id: "c4",
        text: "I usually stick with it by setting small milestones and realistic rules.",
        statModifiers: { discipline: 24, focus: 20 },
        archetypeWeight: { strategist: 5, guardian: 4 },
      },
      {
        id: "c5",
        text: "I am highly consistent — once a habit is forged, it becomes second nature.",
        statModifiers: { discipline: 30, focus: 24 },
        archetypeWeight: { guardian: 7, strategist: 6 },
      },
    ],
  },
  {
    id: "q3_focus",
    number: 3,
    category: "Deep Focus",
    categoryIcon: "🎯",
    prompt: "How easily can you stay focused on one important task without getting distracted?",
    subtitle: "Focus measures your capacity to shield attention from notifications and impulses.",
    options: [
      {
        id: "f1",
        text: "Difficult — I frequently switch between tabs, notifications, and thoughts.",
        statModifiers: { focus: 6, energy: 10 },
        archetypeWeight: { explorer: 3 },
      },
      {
        id: "f2",
        text: "Moderate — I can focus for 15–20 minutes before needing a break or novelty.",
        statModifiers: { focus: 14, intellect: 12 },
        archetypeWeight: { builder: 3 },
      },
      {
        id: "f3",
        text: "Solid — Once I enter a groove, I can sustain 45–60 minutes of deep immersion.",
        statModifiers: { focus: 22, discipline: 18 },
        archetypeWeight: { strategist: 5, scholar: 4 },
      },
      {
        id: "f4",
        text: "Laser focus — I enter deep flow states where hours pass without noticing distractions.",
        statModifiers: { focus: 28, intellect: 22 },
        archetypeWeight: { strategist: 7, scholar: 6 },
      },
    ],
  },
  {
    id: "q4_learning",
    number: 4,
    category: "Intellect & Learning",
    categoryIcon: "🧠",
    prompt: "When you become interested in a new subject, how do you learn?",
    subtitle: "Your cognitive style reveals how your character expands their mental codex.",
    options: [
      {
        id: "l1",
        text: "I skim the highlights and learn just enough to get the gist.",
        statModifiers: { intellect: 8, energy: 12 },
        archetypeWeight: { explorer: 4 },
      },
      {
        id: "l2",
        text: "I learn hands-on by immediately tinkering, building, or breaking things.",
        statModifiers: { intellect: 18, strength: 14 },
        archetypeWeight: { builder: 6, warrior: 3 },
      },
      {
        id: "l3",
        text: "I read articles, watch breakdowns, and follow structured courses step-by-step.",
        statModifiers: { intellect: 24, focus: 18 },
        archetypeWeight: { scholar: 5, strategist: 4 },
      },
      {
        id: "l4",
        text: "I dive down deep rabbit holes — reading source texts, research, and underlying mechanics.",
        statModifiers: { intellect: 30, focus: 24 },
        archetypeWeight: { scholar: 8 },
      },
    ],
  },
  {
    id: "q5_creativity",
    number: 5,
    category: "Creativity & Craft",
    categoryIcon: "✨",
    prompt: "How often do you create, build, write, design, or experiment with original ideas?",
    subtitle: "The spark of creation bridges knowledge into living reality.",
    options: [
      {
        id: "cr1",
        text: "Rarely — I prefer following proven frameworks, routines, or guidelines.",
        statModifiers: { discipline: 16, focus: 12 },
        archetypeWeight: { guardian: 4, strategist: 3 },
      },
      {
        id: "cr2",
        text: "Occasionally — when inspiration strikes or a specific project requires it.",
        statModifiers: { intellect: 14, energy: 12 },
        archetypeWeight: { scholar: 3 },
      },
      {
        id: "cr3",
        text: "Regularly — I consistently tinker with ideas, writing, code, or crafts.",
        statModifiers: { intellect: 22, energy: 20 },
        archetypeWeight: { builder: 6, explorer: 4 },
      },
      {
        id: "cr4",
        text: "Constantly — creating and building original systems is my daily oxygen.",
        statModifiers: { intellect: 28, energy: 26 },
        archetypeWeight: { builder: 8 },
      },
    ],
  },
  {
    id: "q6_social",
    number: 6,
    category: "Social Dynamics",
    categoryIcon: "🤝",
    prompt: "When working toward an ambitious goal, what role feels most natural?",
    subtitle: "Your alignment with comrades, mentors, and the realm community.",
    options: [
      {
        id: "s1",
        text: "The Lone Wolf — I work fastest and best in complete isolation with zero chatter.",
        statModifiers: { focus: 20, discipline: 16 },
        archetypeWeight: { scholar: 4, strategist: 4 },
      },
      {
        id: "s2",
        text: "The Specialist — I like contributing a distinct piece of expertise to a trusted crew.",
        statModifiers: { intellect: 20, focus: 16 },
        archetypeWeight: { builder: 5, scholar: 4 },
      },
      {
        id: "s3",
        text: "The Reliable Anchor — I keep everyone accountable, motivated, and moving smoothly.",
        statModifiers: { discipline: 22, energy: 18 },
        archetypeWeight: { guardian: 7 },
      },
      {
        id: "s4",
        text: "The Catalyst — I rally energy, inspire the vision, and lead the charge into the unknown.",
        statModifiers: { energy: 24, strength: 18 },
        archetypeWeight: { warrior: 6, explorer: 5 },
      },
    ],
  },
  {
    id: "q7_energy",
    number: 7,
    category: "Daily Energy & Vitality",
    categoryIcon: "⚡",
    prompt: "How would you describe your usual physical and mental energy throughout the day?",
    subtitle: "Your internal battery dictates stamina, recovery, and daily resilience.",
    options: [
      {
        id: "e1",
        text: "Low / Sluggish — I often feel fatigued and rely on caffeine or pressure to push through.",
        statModifiers: { energy: 6 },
        archetypeWeight: { scholar: 2 },
      },
      {
        id: "e2",
        text: "Rollercoaster — Sharp spikes of peak intensity followed by sudden steep crashes.",
        statModifiers: { energy: 14, focus: 10 },
        archetypeWeight: { explorer: 4, builder: 3 },
      },
      {
        id: "e3",
        text: "Steady & Moderate — Reliable stamina that carries me through standard obligations.",
        statModifiers: { energy: 20, discipline: 18 },
        archetypeWeight: { guardian: 4, strategist: 4 },
      },
      {
        id: "e4",
        text: "High & Vibrant — Energetic from sunrise to evening with fast recovery between challenges.",
        statModifiers: { energy: 28, strength: 22 },
        archetypeWeight: { warrior: 6, explorer: 5 },
      },
    ],
  },
  {
    id: "q8_habits",
    number: 8,
    category: "Daily Routines",
    categoryIcon: "🧭",
    prompt: "Which statement best describes your daily morning and evening routines?",
    subtitle: "Routines are the sacred rituals that anchor your character across days.",
    options: [
      {
        id: "h1",
        text: "Chaotic — Every day is completely different; I react to whatever happens first.",
        statModifiers: { energy: 10 },
        archetypeWeight: { explorer: 3 },
      },
      {
        id: "h2",
        text: "Loose structure — I have general intentions, but they frequently drift.",
        statModifiers: { discipline: 12, focus: 10 },
        archetypeWeight: { builder: 3 },
      },
      {
        id: "h3",
        text: "Solid anchors — I maintain 2–3 key anchor habits (morning prep, sleep time, workout).",
        statModifiers: { discipline: 20, energy: 18 },
        archetypeWeight: { strategist: 4, guardian: 4 },
      },
      {
        id: "h4",
        text: "Locked in — My mornings and evenings are precision rituals that set me up for victory.",
        statModifiers: { discipline: 28, focus: 22 },
        archetypeWeight: { guardian: 6, strategist: 6 },
      },
    ],
  },
  {
    id: "q9_challenge",
    number: 9,
    category: "Challenge Preference",
    categoryIcon: "⚔️",
    prompt: "When facing a difficult, intimidating goal, what motivates you most to conquer it?",
    subtitle: "The fire that ignites your determination when odds look daunting.",
    options: [
      {
        id: "ch1",
        text: "Proving my limits — The thrill of testing my raw strength, endurance, and grit.",
        statModifiers: { strength: 22, discipline: 18 },
        archetypeWeight: { warrior: 7 },
      },
      {
        id: "ch2",
        text: "Mastering the mystery — Cracking an intellectual puzzle that baffles most people.",
        statModifiers: { intellect: 24, focus: 18 },
        archetypeWeight: { scholar: 7 },
      },
      {
        id: "ch3",
        text: "Flawless execution — Designing a foolproof system and carrying it out step by step.",
        statModifiers: { focus: 22, discipline: 20 },
        archetypeWeight: { strategist: 7 },
      },
      {
        id: "ch4",
        text: "Bringing something to life — Seeing the completed artifact or tool exist in the world.",
        statModifiers: { intellect: 20, energy: 20 },
        archetypeWeight: { builder: 7 },
      },
      {
        id: "ch5",
        text: "The uncharted adventure — Walking into unexplored territory just to see what lies beyond.",
        statModifiers: { energy: 22, strength: 16 },
        archetypeWeight: { explorer: 7 },
      },
    ],
  },
  {
    id: "q10_goals",
    number: 10,
    category: "Current Quests & Focus",
    categoryIcon: "🌟",
    prompt: "What areas would you most like to level up in the next few months?",
    subtitle: "Select up to 3 priority growth quests for your starting journey.",
    isMultiSelect: true,
    maxSelections: 3,
    options: [
      {
        id: "g_fitness",
        text: "Physical Power: Build strength, endurance, workouts, and body vitality.",
        statModifiers: { strength: 12 },
        archetypeWeight: { warrior: 2 },
      },
      {
        id: "g_study",
        text: "Intellectual Mastery: Read books, study coding/skills, or gain deep knowledge.",
        statModifiers: { intellect: 12 },
        archetypeWeight: { scholar: 2 },
      },
      {
        id: "g_focus",
        text: "Deep Focus: Conquer procrastination, screen addiction, and fragmented attention.",
        statModifiers: { focus: 12 },
        archetypeWeight: { strategist: 2 },
      },
      {
        id: "g_habits",
        text: "Iron Consistency: Build daily rituals that stick through thick and thin.",
        statModifiers: { discipline: 12 },
        archetypeWeight: { guardian: 2 },
      },
      {
        id: "g_creativity",
        text: "Creative Creation: Ship side projects, write, design, or launch a venture.",
        statModifiers: { energy: 6, intellect: 6 },
        archetypeWeight: { builder: 2 },
      },
      {
        id: "g_wellness",
        text: "Rest & Vitality: Optimize sleep, morning energy, nutrition, and mental peace.",
        statModifiers: { energy: 12 },
        archetypeWeight: { guardian: 2 },
      },
    ],
  },
];
